springdoc.swagger-ui.path: doc.tempsattente.html
server.forward-headers-strategy: native # pour que ce 💩 de Springdoc fonctionne jusqu'au bout en reverse proxy, sinon le protocol passe pas

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
        
  info:
    git:
      mode: full
    
    java:
      enabled: true
